version: '3.5'

services:
  consul:
    image: consul:1.1.0
    ports:
      - 8500:8500
    volumes:
    - ./consul/services.json:/consul/config/services.json

  tg-farm-postgres:
    image: postgres:10-alpine
    container_name: tg-farm-postgres
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    depends_on:
      - consul

  ph-daily-trash-bot:
    image: ph-daily-trash-bot
    container_name: ph-daily-trash-bot
    hostname: localhost
    restart: on-failure
    ports:
      - "8081:8080"
    environment:
#      - PH_TG_API_BOT_PROD_KEY=
#      - PH_TG_API_BOT_PROD_NAME=
#      - PH_TG_API_BOT_PLUS_KEY=
#      - PH_TG_API_BOT_PLUS_NAME=
      - SPING_FLYWAY_ENABLED=false
      - SPRING_JPA_HIBERNATE_DDL-AUTO=none
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_KAFKA_CONSUMER_BOOTSTRAP-SERVERS=kafka:9092
      - SPRING_KAFKA_PRODUCER_BOOTSTRAP-SERVERS=kafka:9092
      - KAFKA_LOG_TOPIC=tg-farm-info
    depends_on:
      - tg-farm-postgres
      - consul

#  PD_panty_of_destiny_bot:
#    image: pd-panty-of-destiny-bot
#    container_name: panty_of_destiny_bot
#    hostname: localhost
#    restart: on-failure
#    ports:
#      - "8080:8080"
#    environment:
##      - POD_TG_API_BOT_KEY=
##      - POD_TG_API_BOT_CHAT=
##      - POD_TG_API_BOT_SECURE=
#      - SPRING_LIQUIBASE_ENABLED=false
#      - SPRING_JPA_HIBERNATE_DDL-AUTO=none
#      - SPRING_CLOUD_CONSUL_HOST=consul
#      - SPRING_CLOUD_CONSUL_PORT=8500
#      - SPRING_KAFKA_CONSUMER_BOOTSTRAP-SERVERS=kafka:9092
#      - SPRING_KAFKA_PRODUCER_BOOTSTRAP-SERVERS=kafka:9092
#      - KAFKA_LOG_TOPIC=tg-farm-info
#    depends_on:
#      - tg-farm-postgres
#      - consul

networks:
  default:
    external:
      name: tg-farm



