tg:
  bot:
    mnemonic: PH_BT

spring:
  flyway:
    locations: classpath:db/migration/
    enabled: false
    baselineOnMigrate: true

  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: none
#      ddl-auto: create
#      ddl-auto: update


ph:
  tg:
    api:
      bot:
        prod:
          key: ${TG_BOT_PROD_KEY:1439651637:AAGjZOTxQaI8zaNIdQgpcYxsLVzM5GaqqgM}
          name: ${TG_BOT_PROD_NAME:@dev_ph_prod_bot}
        plus:
          key: ${TG_BOT_PLUS_KEY:dev_ph_plus_bot:1417700815:AAF5ChPfCe2a2tkC4yitWpKQFpTTwFwn3EA}
          name: ${TG_BOT_PLUS_NAME:@dev_ph_plus_bot}
      setting:
        cookie: ${API_BOT_COOKIE}
        resource: ${API_BOT_RESOURCE}
        page:
          count: ${PAGE_COUNT}
cloud:
  postgres:
    instance: tg-farm-postgres




